# Generated by Django 3.0.6 on 2020-06-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('gender', models.CharField(default='NA', max_length=10)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('address', models.TextField()),
                ('country', models.CharField(max_length=50)),
                ('joindate', models.DateField()),
                ('upload_file', models.FileField(upload_to='documents')),
            ],
        ),
    ]
