# Generated by Django 3.0.6 on 2020-06-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rivera', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name_plural': 'Members'},
        ),
        migrations.RemoveField(
            model_name='members',
            name='upload_file',
        ),
    ]
