# Generated by Django 3.0.6 on 2020-06-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivera', '0003_auto_20200615_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='upload_file',
            field=models.FileField(upload_to='documents'),
        ),
    ]
