# Generated by Django 3.0.6 on 2020-06-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivera', '0004_auto_20200615_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=20)),
                ('upload_file', models.FileField(upload_to='documents')),
            ],
            options={
                'verbose_name_plural': 'Employee Images',
            },
        ),
    ]
