# Generated by Django 3.0.6 on 2020-06-22 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rivera', '0005_employeedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='email',
            new_name='mail',
        ),
    ]
