# Generated by Django 3.0.6 on 2020-06-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivera', '0006_auto_20200622_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=20)),
                ('mail', models.EmailField(default='None', max_length=254)),
                ('phone', models.CharField(default='None', max_length=10)),
                ('city', models.CharField(default='None', max_length=50)),
                ('country', models.CharField(default='None', max_length=50)),
                ('arrive', models.DateField(default='1990-06-06')),
                ('depart', models.DateField(default='1990-06-06')),
                ('people', models.IntegerField()),
                ('room', models.CharField(default='None', max_length=10)),
                ('bedding', models.CharField(default='None', max_length=10)),
                ('comments', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Guests',
            },
        ),
        migrations.DeleteModel(
            name='guests',
        ),
    ]
