# Generated by Django 3.0.6 on 2020-06-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rivera', '0008_auto_20200622_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='password',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='guest',
            name='username',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
